version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:5001"
    env_file:
      - ./backend/${ENV_FILE}
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/${ENV_FILE}
    networks:
      - mynet

networks:
  mynet:
    driver: bridge