version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:5001"
    env_file:
      - ./backend/${ENV_FILE}

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - ./frontend/${ENV_FILE}
